markdown: redcarpet
baseurl: /akashsingh.github.io
exclude: [READMD.md,vendor]
languages: ["en", "de"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: en
languageNames:
  de: Deutsch
  en: English
sass:
  style: compressed